### PR TITLE
Fix/william/scram

### LINKED ISSUE #12860: Enhanced Authentication Failed with Reason Code 135 (Not Authorized).
### What happened?

I was trying to test MQTT 5.0 enhanced authentication feature. Currently, EMQX has SCRAM authentication supported. 
Here's the details about the configuration and the encountered issues:
1. Create MQTT 5.0 enhanced authentication SCRAM through EMQX dashboard, with Password Hash set to sha256.
2. Create a user with username = "user1", password = "123456".
3. Connect to the broker using enhanced authentication.
4. Broker responded with ConAck with reason: "NotAuthorized".
image

On the MQTT client side, I utilized [rustbase_scram](https://docs.rs/rustbase-scram/latest/rustbase_scram/) crate for calculating the client first and client final messages. I also experimented with a python version SCRAM library, available [here](https://pypi.org/project/scramp/#scramp-scramclient). Both RUST SCRAM and Python SCRAM generates the same client proof using the same client first and server first messages. This suggests that the client proof sent from the client is accurate. So I guess there might be another factor causing the authentication failure. Could you offer any advice on this matter? Additontally, I've included EMQX log information for further reference.

### What did you expect to happen?

More detailed information about the failure.

### How can we reproduce it (as minimally and precisely as possible)?

_No response_

### Anything else we need to know?

_No response_

### EMQX version

Version: 5.5.1
Installed through Docker package.

### OS version

_No response_

### Log files

### PR DESCRIPTION
**Pull request by qzhuyan**
fix : https://github.com/emqx/emqx/issues/12860

strictly following RFC5802

- use ',' separator while construct `AuthMessage`
- fix salted_password internal representation.  

add port program prebuilt bin for interop tests with https://docs.rs/rustbase-scram/latest/rustbase_scram/

### CODE REVIEW

File: src/esasl_scram.erl [hunk 1]
```diff
@@ -445,7 +450,7 @@ nonce() ->
 
 salted_password(Alg, Password, Salt, IterationCount) ->
     {ok, Bin} = pbkdf2:pbkdf2({hmac, Alg}, Password, Salt, IterationCount),
```
Comment (qzhuyan) [inline src/esasl_scram.erl:452]: prefer to use `crypto:pbkdf2_hmac` since OTP 24.2

**Review by tigercl — APPROVED** [review]

**Review by zmstone — APPROVED** [review]
